org: matheussn
app: job-posting-check
service: job-posting-check-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  receiver:
    handler: index.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:654327621199:xyz.fifo
          batchSize: 1

plugins:
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline:
    lambdaPort: 3003